export const MATTER_TREE = [
  {
    id: 'strings',
    icon: '〰️',
    unlocked: true,
    elements: [
      { id: 'open-strings' },
      { id: 'closed-strings' },
      { id: 'superstrings' },
      { id: 'heterotic-strings' },
      { id: 'branes' },
      { id: 'kaluza-klein' },
      { id: 'd-branes' },
    ],
  },
  {
    id: 'gauge-bosons',
    icon: '⚡',
    unlocked: false,
    elements: [
      { id: 'photons' },
      { id: 'gluons' },
      { id: 'w-bosons' },
      { id: 'z-bosons' },
      { id: 'higgs-bosons' },
      { id: 'gravitons' },
      { id: 'axions' },
    ],
  },
  {
    id: 'quarks',
    icon: '🔬',
    unlocked: false,
    elements: [
      { id: 'up-quarks' },
      { id: 'down-quarks' },
      { id: 'strange-quarks' },
      { id: 'charm-quarks' },
      { id: 'bottom-quarks' },
      { id: 'top-quarks' },
    ],
  },
  {
    id: 'leptons',
    icon: '🌀',
    unlocked: false,
    elements: [
      { id: 'electrons' },
      { id: 'muons' },
      { id: 'tau-leptons' },
      { id: 'electron-neutrinos' },
      { id: 'muon-neutrinos' },
      { id: 'tau-neutrinos' },
    ],
  },
  {
    id: 'hadrons',
    icon: '⚛️',
    unlocked: false,
    elements: [
      { id: 'protons' },
      { id: 'neutrons' },
      { id: 'pions' },
      { id: 'kaons' },
      { id: 'hyperons' },
      { id: 'mesons' },
      { id: 'baryons' },
    ],
  },
  {
    id: 'atoms',
    icon: '🔵',
    unlocked: false,
    elements: [
      { id: 'hydrogen' },
      { id: 'helium' },
      { id: 'carbon' },
      { id: 'oxygen' },
      { id: 'nitrogen' },
      { id: 'silicon' },
      { id: 'iron' },
    ],
  },
  {
    id: 'heavy-atoms',
    icon: '🟡',
    unlocked: false,
    elements: [
      { id: 'copper' },
      { id: 'silver' },
      { id: 'gold' },
      { id: 'lead' },
      { id: 'bismuth' },
      { id: 'tin' },
      { id: 'mercury' },
    ],
  },
  {
    id: 'lanthanides',
    icon: '🟢',
    unlocked: false,
    elements: [
      { id: 'lanthanum' },
      { id: 'cerium' },
      { id: 'praseodymium' },
      { id: 'neodymium' },
      { id: 'samarium' },
      { id: 'europium' },
      { id: 'gadolinium' },
    ],
  },
  {
    id: 'actinides',
    icon: '🔴',
    unlocked: false,
    elements: [
      { id: 'thorium' },
      { id: 'protactinium' },
      { id: 'uranium' },
      { id: 'neptunium' },
      { id: 'plutonium' },
      { id: 'americium' },
      { id: 'curium' },
    ],
  },
  {
    id: 'stars',
    icon: '⭐',
    unlocked: false,
    elements: [
      { id: 'red-dwarfs' },
      { id: 'yellow-dwarfs' },
      { id: 'blue-giants' },
      { id: 'red-giants' },
      { id: 'white-dwarfs' },
      { id: 'brown-dwarfs' },
      { id: 'supergiants' },
    ],
  },
  {
    id: 'star-clusters',
    icon: '✨',
    unlocked: false,
    elements: [
      { id: 'open-clusters' },
      { id: 'globular-clusters' },
      { id: 'stellar-associations' },
      { id: 'moving-groups' },
      { id: 'star-forming-regions' },
      { id: 'nebular-clusters' },
      { id: 'super-star-clusters' },
    ],
  },
  {
    id: 'stellar-remnants',
    icon: '💫',
    unlocked: false,
    elements: [
      { id: 'neutron-stars' },
      { id: 'pulsars' },
      { id: 'stellar-black-holes' },
      { id: 'magnatars' },
      { id: 'quark-stars' },
      { id: 'planetary-nebulas' },
      { id: 'supernova-remnants' },
    ],
  },
  {
    id: 'galaxies',
    icon: '🌌',
    unlocked: false,
    elements: [
      { id: 'spiral-galaxies' },
      { id: 'elliptical-galaxies' },
      { id: 'quasars' },
      { id: 'barred-galaxies' },
      { id: 'lenticular-galaxies' },
      { id: 'irregular-galaxies' },
      { id: 'dwarf-galaxies' },
    ],
  },
  {
    id: 'large-scale-structures',
    icon: '🕸️',
    unlocked: false,
    elements: [
      { id: 'galaxy-filaments' },
      { id: 'galaxy-walls' },
      { id: 'voids' },
      { id: 'superclusters' },
      { id: 'great-walls' },
      { id: 'lya-forests' },
      { id: 'reionization-structures' },
    ],
  },
  {
    id: 'cosmic-phenomena',
    icon: '🌠',
    unlocked: false,
    elements: [
      { id: 'supermassive-black-holes' },
      { id: 'galaxy-clusters' },
      { id: 'cosmic-strings' },
      { id: 'dark-matter' },
      { id: 'dark-energy' },
      { id: 'cosmic-microwave-background' },
      { id: 'gravitational-waves' },
    ],
  },
  {
    id: 'universes',
    icon: '🌍',
    unlocked: false,
    elements: [
      { id: 'inflationary-universe' },
      { id: 'multiverse' },
      { id: 'cyclic-universe' },
      { id: 'bubble-universe' },
      { id: 'holographic-universe' },
      { id: 'quantum-foam' },
      { id: 'ekpyrotic-universe' },
    ],
  },
];

export const ANTI_MATTER_TREE = [
  {
    id: 'anti-strings',
    icon: '〰️',
    unlocked: true,
    elements: [
      { id: 'anti-open-strings' },
      { id: 'anti-closed-strings' },
      { id: 'anti-superstrings' },
      { id: 'anti-heterotic-strings' },
      { id: 'anti-branes' },
      { id: 'anti-kaluza-klein' },
      { id: 'anti-d-branes' },
    ],
  },
  {
    id: 'anti-gauge-bosons',
    icon: '🌀',
    unlocked: false,
    elements: [
      { id: 'anti-photons' },
      { id: 'anti-gluons' },
      { id: 'anti-w-bosons' },
      { id: 'anti-z-bosons' },
      { id: 'anti-higgs-bosons' },
      { id: 'anti-gravitons' },
      { id: 'anti-axions' },
    ],
  },
  {
    id: 'anti-quarks',
    icon: '🔬',
    unlocked: false,
    elements: [
      { id: 'anti-up-quarks' },
      { id: 'anti-down-quarks' },
      { id: 'anti-strange-quarks' },
      { id: 'anti-charm-quarks' },
      { id: 'anti-bottom-quarks' },
      { id: 'anti-top-quarks' },
    ],
  },
  {
    id: 'anti-leptons',
    icon: '⚡',
    unlocked: false,
    elements: [
      { id: 'positrons' },
      { id: 'anti-muons' },
      { id: 'anti-tau-leptons' },
      { id: 'anti-electron-neutrinos' },
      { id: 'anti-muon-neutrinos' },
      { id: 'anti-tau-neutrinos' },
    ],
  },
  {
    id: 'anti-hadrons',
    icon: '⚛️',
    unlocked: false,
    elements: [
      { id: 'anti-protons' },
      { id: 'anti-neutrons' },
      { id: 'anti-pions' },
      { id: 'anti-kaons' },
      { id: 'anti-hyperons' },
      { id: 'anti-baryons' },
    ],
  },
  {
    id: 'anti-atoms',
    icon: '🔵',
    unlocked: false,
    elements: [
      { id: 'anti-hydrogen' },
      { id: 'anti-helium' },
      { id: 'anti-carbon' },
      { id: 'anti-oxygen' },
      { id: 'anti-nitrogen' },
      { id: 'anti-silicon' },
    ],
  },
  {
    id: 'anti-heavy-atoms',
    icon: '🟡',
    unlocked: false,
    elements: [
      { id: 'anti-copper' },
      { id: 'anti-silver' },
      { id: 'anti-gold' },
      { id: 'anti-lead' },
      { id: 'anti-bismuth' },
      { id: 'anti-tin' },
    ],
  },
  {
    id: 'anti-lanthanides',
    icon: '🟢',
    unlocked: false,
    elements: [
      { id: 'anti-lanthanum' },
      { id: 'anti-cerium' },
      { id: 'anti-praseodymium' },
      { id: 'anti-neodymium' },
      { id: 'anti-samarium' },
      { id: 'anti-europium' },
    ],
  },
  {
    id: 'anti-actinides',
    icon: '🔴',
    unlocked: false,
    elements: [
      { id: 'anti-thorium' },
      { id: 'anti-protactinium' },
      { id: 'anti-uranium' },
      { id: 'anti-neptunium' },
      { id: 'anti-plutonium' },
      { id: 'anti-americium' },
    ],
  },
  {
    id: 'anti-stars',
    icon: '🌟',
    unlocked: false,
    elements: [
      { id: 'anti-red-dwarfs' },
      { id: 'anti-yellow-dwarfs' },
      { id: 'anti-blue-giants' },
      { id: 'anti-red-giants' },
      { id: 'anti-white-dwarfs' },
      { id: 'anti-brown-dwarfs' },
    ],
  },
  {
    id: 'anti-star-clusters',
    icon: '✨',
    unlocked: false,
    elements: [
      { id: 'anti-open-clusters' },
      { id: 'anti-globular-clusters' },
      { id: 'anti-stellar-associations' },
      { id: 'anti-moving-groups' },
      { id: 'anti-star-forming-regions' },
      { id: 'anti-nebular-clusters' },
    ],
  },
  {
    id: 'anti-stellar-remnants',
    icon: '💫',
    unlocked: false,
    elements: [
      { id: 'anti-neutron-stars' },
      { id: 'anti-pulsars' },
      { id: 'anti-stellar-black-holes' },
      { id: 'anti-magnatars' },
      { id: 'anti-quark-stars' },
      { id: 'anti-supernova-remnants' },
    ],
  },
  {
    id: 'anti-galaxies',
    icon: '🌌',
    unlocked: false,
    elements: [
      { id: 'anti-spiral-galaxies' },
      { id: 'anti-elliptical-galaxies' },
      { id: 'anti-quasars' },
      { id: 'anti-barred-galaxies' },
      { id: 'anti-irregular-galaxies' },
      { id: 'anti-dwarf-galaxies' },
    ],
  },
  {
    id: 'anti-large-scale-structures',
    icon: '🕸️',
    unlocked: false,
    elements: [
      { id: 'anti-galaxy-filaments' },
      { id: 'anti-galaxy-walls' },
      { id: 'anti-superclusters' },
      { id: 'anti-voids' },
      { id: 'anti-great-walls' },
    ],
  },
  {
    id: 'anti-cosmic-phenomena',
    icon: '🌠',
    unlocked: false,
    elements: [
      { id: 'anti-supermassive-black-holes' },
      { id: 'anti-galaxy-clusters' },
      { id: 'anti-cosmic-strings' },
      { id: 'anti-dark-matter' },
      { id: 'anti-dark-energy' },
      { id: 'anti-gravitational-waves' },
    ],
  },
  {
    id: 'anti-universes',
    icon: '🌐',
    unlocked: false,
    elements: [
      { id: 'anti-inflationary-universe' },
      { id: 'anti-multiverse' },
      { id: 'anti-cyclic-universe' },
      { id: 'anti-bubble-universe' },
      { id: 'anti-holographic-universe' },
      { id: 'anti-ekpyrotic-universe' },
    ],
  },
];
